### ISSUE TITLE
The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by sunnytranco** [trilbymedia/grav-plugin-git-sync#39]
When I finish step 3 of the wizard, this error shows up:

`error: The requested URL returned error: 403 Forbidden while accessing https://sunnytranco:{password}@github.com/sunnytranco/gravLearn2.git/info/refs fatal: HTTP request failed`

I've already tested my connection, it's fine

**Comment by w00fz** [comment]
Make sure the password is actually correct, I know it sounds like a stupid advice but I did have this issue myself before 😃. Also, if you are using 2FA with GitHub, you cannot use the actual password from remote, you need to create an Access Token and use that instead of your password.

**Comment by YuriyKartuzov** [comment]
I'm having this issue on public repo, which was private before. This means there are no passwords to be entered

**Comment by w00fz** [comment]
You do still a password even if it's public. The authentication is required in order to guarantee you have PUSH permissions.

**Comment by Amina-Zafar** [comment]
how can I create an access token

**Comment by Amina-Zafar** [comment]
![image](https://user-images.githubusercontent.com/45695011/53827072-07cf8780-3f9c-11e9-8f6a-0bfe7d354a42.png)
the error is this even after doing this
![image](https://user-images.githubusercontent.com/45695011/53827124-34839f00-3f9c-11e9-973b-8e11f69fa3c4.png)

**Comment by paulhibbitts** [comment]
Hi @Amina-Zafar , it depends on the Git-based service you are using. For example, with GitHub you could create a token at `https://github.com/settings/tokens`

**Comment by Amina-Zafar** [comment]
Thanks

**Comment by Amina-Zafar** [comment]
unable to push my code into my current account, getting access denied 403 error. I have tried many options making new repos, by changing drive, even created repo on Bitbucket but still, my repo is associated with my colleague GitHub account. Please guide me how can I resolve this issue?

**Comment by paulhibbitts** [comment]
Did you follow these steps https://www.youtube.com/watch?v=avcGP0FAzB8 (interface slightly different now)? Are you getting any error messages?

**Comment by Amina-Zafar** [comment]
Thanks a lot, i will check it

**Comment by Amina-Zafar** [comment]
I have viewed this video but this is not my problem solution. Actually, my repo is public and my colleague repo is also public. The problem is, I am unable to push my code into my account repo this is the main problem that I am facing. Please help me.

**Comment by Amina-Zafar** [comment]
Moreover, when I push my code into GitHub then give the error, 'access denied from my colleague account', which is no more login on my laptop.

**Comment by paulhibbitts** [comment]
This sounds less like a GitSync Plugin issue and more of a Git/GitHub issue... sorry but I don't think I can be of any help with that.

**Comment by Amina-Zafar** [comment]
It's okay

**Comment by habibakij** [comment]
fatal: unable to access 'https://github.com/habibakij/Testing.git/': The requested URL returned error: 403
i face this problem.. username habibakij

**Comment by ali-alzobaidi** [comment]
l

**Comment by ali-alzobaidi** [comment]
ماله حل

**Comment by AndABond** [comment]
> fatal: unable to access 'https://github.com/habibakij/Testing.git/': The requested URL returned error: 403
> i face this problem.. username habibakij

Did you manage to fix this error, Facing the same thing

**Comment by KirilNit** [comment]
Have the same issue with my repo. Who managed this or anyone who can help?

**Comment by w00fz** [comment]
That error means you are using wrong credential or wrong repo:

1. Username needs to be the user, not the email
2. Ensure you provide the proper password. If you have 2FA enabled on GitHub, you need to make sure you create an Access Token with proper access permissions and use the token as password instead.
3. Repo format is: `https://github.com/<user>/<repo>.git`

403 means GitHub is not granting you access so one or more of the 3 things above are the problem

**Comment by kirtanwadekar** [comment]
Can anyone please help me ASAP, with below-mentioned error on cmd terminal of vscode while the last step(git push -u origin master) to push my project.

D:\ReactJS Projects\resort>git push -u origin master
remote: Permission to kirtanwadekar/react-beach-resort-recording.git denied to kabir19.
fatal: unable to access 'https://github.com/kirtanwadekar/react-beach-resort-recording.git/': The requested URL returned error: 403

D:\ReactJS Projects\resort>

**Comment by w00fz** [comment]
403 means credentials errors or that you don’t have permission to push.

**Comment by ysh329** [comment]
same error

**Comment by ILLYAS-DEULECT** [comment]
The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
For Windows you can find the keys here:

control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next, remove the Github keys.

In mac
1-In Finder, search for the Keychain Access app.
2In Keychain Access, search for github.com.
3-Find the "internet password" entry for github.com.
4-Edit or delete the entry accordingly.

**Comment by rajunerugatti123** [comment]
$ git push origin master
remote: Permission to rajunerugatti123/secondrepo.git denied to nerugattiraju1234.
fatal: unable to access 'https://github.com/rajunerugatti123/secondrepo.git/': The requested URL returned error: 403
i will get this type of error. how it can solve

**Comment by orangefruity** [comment]
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/orangefruity/test.git/info/refs

**Comment by kiranashav** [comment]
Hi People,

ILLYAS-DEULECT has already given us the answer. I was facing the same problem mentioned by rajunerugatti123, w00fz, Amina-Zafar . I followed the steps below and was able to resolve the issue


The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
For Windows you can find the keys here:

control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next, remove the Github keys.

In mac
1-In Finder, search for the Keychain Access app.
2In Keychain Access, search for github.com.
3-Find the "internet password" entry for github.com.
4-Edit or delete the entry accordingly.

**Comment by bharathreddymuddarla** [comment]
I had the same issue and the solution provided by ILLYAS-DEULECT worked.

Thank you ILLYAS-DEULECT

**Comment by rafaelacnh** [comment]
Eu tive o mesmo problema e a solução fornecida pela ILLYAS-DEULECT funcionou.

**Comment by Amanjakhetiya** [comment]
I had also tried to resolve the issue with the method provided by  ILLYAS-DEULECT but when i again git push , a prompt box appears and it asks for login details and hence github credentials are again saved and so the problem still continues.Please help me with this.

**Comment by bitcot** [comment]
It could be because you are trying to access private repo and payment plan has expired and subsequent payment is not going through due to incorrect payment details.

**Comment by Vikash79** [comment]
thanks this works - 

control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next, remove the Github keys.

**Comment by FatymaHamdani** [comment]
Tx "kiranashav"

Solution for this problem is : 
control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next, remove the Github keys.

In mac
1-In Finder, search for the Keychain Access app.
2In Keychain Access, search for github.com.
3-Find the "internet password" entry for github.com.
4-Edit or delete the entry accordingly.

**Comment by PersickWebdev** [comment]
Thanks a lot! 
The solution has worked :)

**Comment by niravshah241** [comment]
Changing password worked for me.

**Comment by sanjeevgithub4** [comment]
> Tx "kiranashav"
> 
> Solution for this problem is :
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

This worked for me. Thanks a lot..!!

**Comment by vogelPaul** [comment]
can you be more clear please?
when i got this:
 '''control panel > user accounts > credential manager > Windows credentials > Generic credentials''', i want to know what i have to do exactly??

""""Next, remove the Github keys."""", so how to remove githud key??
<img width="523" alt="git" src="https://user-images.githubusercontent.com/54835094/71583616-94ae8780-2b52-11ea-82ea-04e40ecee8fc.png">

**Comment by AuxousTechnology** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

Love u sir

**Comment by AuxousTechnology** [comment]
**Problems:-**
remote: Permission to AuxousTechnology/skulous.git denied to bikashsingh-au7.
fatal: unable to access 'https://github.com/AuxousTechnology/skulous.git/': The requested URL returned error: 403

**Solutions**
You can solve this problem by using lots of methods. But below simple method is written which helps you to solve these issues.

step 1: go to control panel 
step-2: then go to user accounts 
step 3: After that go to credential manager
step 4: then Windows credentials
step 5: go to Generic credentials
step 6: finally delete the Github keys.

After done above all the steps then use the push command
->git push -u origin master

After that, you would see a GitHub login form windows will appear. Then you need to log in with your GitHub email and password.
After login, you can use push command it will 110% work.

**Comment by BoschGuru** [comment]
Also check your company VPN/Proxy

**Comment by richardaquino** [comment]
Removing Github keys work in windows credentials

**Comment by reddyshalinisv** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

thank you

**Comment by reddyshalinisv** [comment]
thanku

**Comment by sdjebali** [comment]
Hello,
I personnally solved this problem by doing the following on the command line
git remote set-url origin https://yourusername@github.com/user/repo.git
Best,

**Comment by edubodhi** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

Thanks a lot. It worked/

**Comment by TrevorNathan** [comment]
Thanks @sdjebali it worked perfectly

**Comment by ravindrahomework** [comment]
Thanks Illyas632

**Comment by Adilet121286** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

Hi Thank You a lot. I was confusing with this issue for more than 3 days. after reading your comment I solved my problem. Thank you a lot again

**Comment by w00fz** [comment]
Thanks for figuring out and sharing the fix to this issue @m-illyas .

Seems to be an issue mainly related to Windows. Would be great if this was part of the README as a known issue with steps on our to resolve it and perhaps a link to this issue. Is anyone interested in making it a Pull Request?

Thanks!

**Comment by harshacheemakurt** [comment]
> **Problems:-**
> remote: Permission to UserName/repo.git denied to AnotherUserName.
> fatal: unable to access 'https://github.com/UserName/repo.git/': The requested URL returned error: 403
> 
> **Solutions**
> You can solve this problem by using lots of methods. But below simple method is written which helps you to solve these issues.
> 
> step 1: go to control panel
> step-2: then go to user accounts
> step 3: After that go to credential manager
> step 4: then Windows credentials
> step 5: go to Generic credentials
> step 6: finally delete the Github keys.
> 
> After done above all the steps then use the push command
> ->git push -u origin master
> 
> After that, you would see a GitHub login form windows will appear. Then you need to log in with your GitHub email and password.
> After login, you can use push command it will 110% work.

not working

**Comment by w00fz** [comment]
Added a reference to this in https://github.com/trilbymedia/grav-plugin-git-sync#known-issues-and-resolutions

Cheers.

**Comment by preetysangwan30** [comment]
remove the personal access token it will work

**Comment by LuisMauricioFalla** [comment]
> Hi People,
> 
> ILLYAS-DEULECT has already given us the answer. I was facing the same problem mentioned by rajunerugatti123, w00fz, Amina-Zafar . I followed the steps below and was able to resolve the issue
> 
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

THANK YOU MUCH. I'M WORKING ON A COLLEGE COMPUTER AND COULDN'T GET ANYTHING TO WORK, WINDOWS KEEPING CREDENTIALS... fuuuuuuu

**Comment by MicheleL-Intel** [comment]
Suggestion by 'sdjebali' solved the problem for me.  Thanks!

$ git remote set-url <my remote branch> <my github fork URL>.git

**Comment by zhahong** [comment]
> Hello,
> I personnally solved this problem by doing the following on the command line
> git remote set-url origin https://yourusername@github.com/user/repo.git
> Best,

Actually, the exact way is git remote set-url origin +your repository URL, I resolved this issue by this way, also thanks

**Comment by TicketManagementSystemG3** [comment]
> Hi People,
> 
> ILLYAS-DEULECT has already given us the answer. I was facing the same problem mentioned by rajunerugatti123, w00fz, Amina-Zafar . I followed the steps below and was able to resolve the issue
> 
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

how to resolve this issue in linux

**Comment by arverma** [comment]
For **macOS** try this for **https** problem:
`git config --global credential.helper osxkeychain`

Then try pull, push and it should ask for username and password.

**Comment by bhargavshah** [comment]
For **Mac**

If you **have the below setting**
`git config --global credential.helper osxkeychain`

**And your credentials are correct** in the "Keychain Access" app.

**Deleting all the Github internet passwords.** Now when you try to push, Git will try to authenticate you again by asking for username/password, or take you to Github auth page.

**Comment by ckoorosh** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

For those whose problem is not solved in this way...
I strongly recommend to check that you have the permission to push to the repo. To make sure, ask the repo's admin to give you the **WRITE** permission in the '**Manage Access**' section of the repo's settings.
Hope this works for you.

**Comment by kizzanaome** [comment]
> Hi People,
> 
> ILLYAS-DEULECT has already given us the answer. I was facing the same problem mentioned by rajunerugatti123, w00fz, Amina-Zafar . I followed the steps below and was able to resolve the issue
> 
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

what about on Linux... every solution i see is mac or windows what about linux

**Comment by panthia** [comment]
Working again. Thank you.

**Comment by MailMadhu** [comment]
The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
For Windows you can find the keys here:

control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next, remove the Github keys.

Thank you m-illyas  this worked

**Comment by magedhelmy1** [comment]
I cloned a repo, did some edits, and tried to push to my own repo. This gave me the error 

`fatal: unable to access 'https://github.com/matterport/Mask_RCNN.git/': The requested URL returned error: 403`


So I checked

`1. git remote -v`
`2. git remote rm origin`

Checked now that `git remote -v` is empty
Then added the correct URL

` 1. git remote add origin git@github.com:magedhelmy1/x.git`
`2. git push -u origin master`

**Comment by AhmadTesting** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

Such a solid solution although it didn't work completely for my case I have been trying to push my data to a different account SO in order to solve that. 

I had to add two more steps on this solution and it worked just fine. 

`git config --global user.name "new-name"`
`git config --global user.email "email for my second account"`

and that got it to work for me... am not sure why it didn't work without changing the name and email though.

**Comment by hasibaziz37** [comment]
Please correct the path for windows:

    The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
    For Windows you can find the keys here:

    control panel > user accounts > credential manager > Windows credentials > Generic credentials
**_Correct:
    Control panel >  Credential manager > Windows credentials > Generic credentials_**

    Next, remove the Github keys.

    In mac
    1-In Finder, search for the Keychain Access app.
    2In Keychain Access, search for github.com.
    3-Find the "internet password" entry for github.com.
    4-Edit or delete the entry accordingly.

Thank you. Its working fine. Its really helpful. Great

**Comment by Hossanna** [comment]
In trying to push origin master...
Fatal: unable to access 'https://.../': Failed to connect to GitHub.com port 443: Bad access

Please how can I solve this problem

**Comment by Pushp1992** [comment]
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

**Comment by Pushp1992** [comment]
This was the savage reply. It worked well.

**Comment by lqcuong021099** [comment]
help me fix this err:
remote: Permission to lqcuong021099/dog-cat-mouse.git denied to quoccuong021099.
fatal: unable to access 'https://github.com/lqcuong021099/dog-cat-mouse.git/': The requested URL returned error: 403

**Comment by w00fz** [comment]
That error is bad credentials

**Comment by KaishM** [comment]
following @m-illyas steps solved my issue.

**Comment by pk0205** [comment]
while creating personal access token make sure to select scopes.(just selecting repo should be fine)

**Comment by krishnaanji** [comment]
> Make sure the password is actually correct, I know it sounds like a stupid advice but I did have this issue myself before 😃. Also, if you are using 2FA with GitHub, you cannot use the actual password from remote, you need to create an Access Token and use that instead of your password.

**Comment by krishnaanji** [comment]
remove existing credentials in 'windows credentials'

**Comment by caprica-Six** [comment]
I was getting the same _"403 error. Permission to write to gist denied"_, when trying to clone a **gist** repo with **https**.

Repo format is: https://github.com/<user>/<repo>.git

Here's how I fixed it:

- Created Personal Access Token, as per [docs](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).
- Ticked - **gist - Create gists**.
- Login - username, which is user, nor email (as mentioned above)
- Password - this is the Access token - paste 

Now all is working fine.

<img width="511" alt="Screenshot 2021-02-03 at 09 45 24" src="https://user-images.githubusercontent.com/4679901/106728985-ee5e6c80-6604-11eb-9d5c-cf927197b1dc.png">

**Comment by rigov1984** [comment]
> El error puede ser que la computadora haya guardado un nombre de usuario y contraseña de git, por lo que si cambia a otra cuenta, aparecerá el error 403. A continuación se muestra la solución
> para Windows, puede encontrar las claves aquí:
> 
> panel de control> cuentas de usuario> administrador de credenciales> credenciales de Windows> credenciales genéricas
> 
> A continuación, elimine las claves de Github.
> 
> En Mac
> 1-In Finder, busque la aplicación Keychain Access.
> 2 En Acceso a llaveros, busque github.com.
> 3-Busque la entrada "contraseña de Internet" para github.com.
> 4-Edite o elimine la entrada según corresponda.

efectivamente esta solución me sirvió....muchas graciassss.

**Comment by anar1996** [comment]
fatal: unable to access 'https://github.com/blablabla/Annotations.git/': The requested URL returned error: 403
So I tried it now and got an error like this. In my opinion, the reason for this error is indirectly because the other party does not allow the project.

**Comment by Rimpi246** [comment]
> Hi People,
> 
> ILLYAS-DEULECT has already given us the answer. I was facing the same problem mentioned by rajunerugatti123, w00fz, Amina-Zafar . I followed the steps below and was able to resolve the issue
> 
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> 
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.

Hello...I did the same but the error still persists. What do I do ?

**Comment by alhamidysattam** [comment]
help 
:)

**Comment by MRRaihan** [comment]
> Please correct the path for windows:
> 
> ```
> The error may be, the computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
> For Windows you can find the keys here:
> 
> control panel > user accounts > credential manager > Windows credentials > Generic credentials
> ```
> 
> **_Correct: Control panel > Credential manager > Windows credentials > Generic credentials_**
> 
> ```
> Next, remove the Github keys.
> 
> In mac
> 1-In Finder, search for the Keychain Access app.
> 2In Keychain Access, search for github.com.
> 3-Find the "internet password" entry for github.com.
> 4-Edit or delete the entry accordingly.
> ```
> 
> Thank you. Its working fine. Its really helpful. Great

**Comment by MRRaihan** [comment]
Thank you. Its working fine. Its really helpful. Great
