### ISSUE TITLE
Fatal https error in wizard

### ISSUE THREAD

**Issue by cpopell** [trilbymedia/grav-plugin-git-sync#8]
When trying to test connection I get

> fatal: I don't handle protocol ''https'

(yes, with the incorrect apostrophes). I tried following your advice and set my git path to 

>C:/Program Files/Git/bin/git.exe

However, it thinks git isn't installed if I do that. I'm running on MAMP.

**Comment by w00fz** [comment]
Can you try creating a folder somewhere in your machine and running the command `git.exe https://github.com/trilbymedia/grav-plugin-git-sync.git`, do you get the same error?

**Comment by w00fz** [comment]
I was able to reproduce this issue with MAMP on Windows! Going to see what's going on with that.

**Comment by w00fz** [comment]
Have you tried going past the Test connection, save as is and still trying to use it?

**Comment by cpopell** [comment]
I can try! I guess I can just backup my entire folder before going ahead, just in case. Should I still run that command?

**Comment by w00fz** [comment]
Hey @cpopell , I just released the RC3 testing version that should address the windows issue, could you please upgrade to that and try? You can revert the binary execution reference to the default empty value, there's no need to specify that anymore.

Also, in case the errors persist, I added a new option in the Advanced section that allows to enable logging for Git commands executions. Enabling that should add more details in the `logs/grav.log` that could be useful information to figure out what's the error.

Let me know, thanks.

**Comment by cpopell** [comment]
This is an interesting error--I got it before, but I just downloaded manually to replace the plugin. I thought you should see it anyway, just in case. Would you prefer I try manually downloading?

![image](https://cloud.githubusercontent.com/assets/6355439/22133223/e888794e-de73-11e6-82c5-de817b08b450.png)

**Comment by cpopell** [comment]
Manually downloaded and replaced. Seems to be working now.

**Comment by cpopell** [comment]
Oh god, I hate everything.

Installed Heroku, which uninstalled and reinstalled git for some reason, and now git-sync can't see git at all--even though I tried reinstalling the version that was previously working.

Sorry for all the pain, hah!

**Comment by w00fz** [comment]
Good to know it works now! And yah that error you reported I actually caught myself when I was debugging on windows.
I already fixed this in Admin plugin, it will be good at next release. Worth noticing the issue only affects testing plugins and trying to install/update on Windows.

The plugin itself shouldn't have anything to do with git getting removed, it's probably something to do with the server setup.

**Comment by cpopell** [comment]
Git is still accessible via CLI (cmd.exe), it looks like Grav just can't see it.

**Comment by w00fz** [comment]
Check your `user/config/plugins/git-sync.yaml` and make sure the `git.bin` entry has just `git` as value.

```yaml
git:
  name: GitSync
  email: gitsync@getgrav.org
  bin: git
```

**Comment by cpopell** [comment]
That is, in fact, what it says. So, going to a backup, it also isn't seeing Git.

I tried uninstalling and reinstalling git. It's still available via CLI, and Grav still isn't seeing it.

**Comment by w00fz** [comment]
I'm really not too sure why php would stop seeing git, this seems to be beyond GitSync scope though, perhaps try setting up a new grav+gitsync install from scratch?
Sounds like it was working fine before you reinstalled heroku, something with the PATH or the windows environment must have gone out of whack.
I'm unfortunately not too familiar with that setup.

**Comment by w00fz** [comment]
Were you able to resolve this @cpopell ?

**Comment by w00fz** [comment]
Feel free to reopen if you have anything else to add to the issue or you still have problems with it!

Cheers.
